= Role-based access control Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-role-based-access-control/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-role-based-access-control/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="2*", options="header"]
|===
^|onRequest
^|onResponse

^.^| X
^.^|

|===

== Description

The Role-Based Access Control policy (RBAC policy) checks access to the resource by providing required roles to access it.

The policy can be configured to allow only requests which have roles exactly matching configured roles (strict mode).
The other option is to ensure that tje incoming request contains at least one role matching configured roles.

== Configuration

|===
|Property |Required |Description |Type| Default

.^|roles
^.^|X
|The list of required roles.
^.^|Array of string
|

.^|strict
^.^|X
|When access token is validated, the token endpoint payload is saved under the ```oauth.payload``` context attribute.
^.^|boolean
^.^|true

|===

[source, json]
.RBAC Policy example:
----
{
  "rbac": {
    "roles": ["read", "write", "admin"],
    "strict": true
  }
}
----

== Http Status Code

|===
|Code |Message

.^| ```400```
| In case of:

* The roles associated to the request are not valid.

.^| ```403```
| In case of:

* No role associated to the current request

* Role(s) associated to the request does not match required role(s).

|===

== Errors
If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys send by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|RBAC_NO_USER_ROLE (403)
^.^|-
.^|RBAC_INVALID_USER_ROLES (400)
^.^|-
.^|RBAC_FORBIDDEN (403)
^.^|-

|===